name: drake_2_0_app
description: TMDrake Drake 2.0 Companion App - easy BLE control for the dragonsuit tail.
publish_to: 'none'
version: 0.2.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.0
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tmdrake_badge.png
    - assets/tmdrake_icon.png
